version: '3.4'

services:
  olmag.identity.api:
    image: ${DOCKER_REGISTRY-}olmagidentityapi
    build:
      context: .
      dockerfile: OlMag.Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8781
      - ASPNETCORE_Kestrel__Certificates__Default__User=olmag_identity
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123asdASD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx      
    ports:
      - 8781:8781
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro
    networks:
      - identity
      
  olmagidentitydb:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: olmagidentitydb
    environment:
      POSTGRES_PASSWORD: 123asdASD
      POSTGRES_DB: olmag.identity
      POSTGRES_USER: olmag_identity
    command: -c shared_buffers=128MB -c max_connections=200 -c max_prepared_transactions=200 -c effective_cache_size=384GB -c maintenance_work_mem=2GB -c checkpoint_completion_target=0.7 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=335544kB -c min_wal_size=1GB -c max_wal_size=4GB
    ports:
      - 5732:5432
    volumes:
      - olmagidentitydb:/var/lib/postgresql/data
    networks:
      - identity

volumes:
  olmagidentitydb:
  pgadmin:
      
networks:
  identity:
    name: identity
